window.KBC_DEMO = {
  emma: {
    name: "Emma",
    balance: 3842.61,
    greeting: "Good evening, Emma",
    transactions: [
      {
        id: "1",
        merchant: "Rental deposit",
        category: "Housing",
        amount: -2100,
        date: "Sep 14",
        signal: "HOUSING",
      },
      {
        id: "2",
        merchant: "IKEA",
        category: "Home",
        amount: -847,
        date: "Sep 12",
        signal: "HOME",
      },
      {
        id: "3",
        merchant: "Brico",
        category: "Home improvement",
        amount: -213,
        date: "Sep 10",
        signal: "HOME",
      },
      {
        id: "4",
        merchant: "Cambio",
        category: "Van rental",
        amount: -64,
        date: "Sep 9",
        signal: "MOVING",
      },
      {
        id: "5",
        merchant: "Salary",
        category: "Income",
        amount: 2850,
        date: "Sep 1",
      },
      {
        id: "6",
        merchant: "Colruyt",
        category: "Groceries",
        amount: -68.42,
        date: "Aug 30",
      },
    ],
  },
  noah: {
    name: "Noah",
    balance: 1248.3,
    greeting: "Good evening, Noah",
    transactions: [
      {
        id: "n1",
        merchant: "First salary",
        category: "Income",
        amount: 2100,
        date: "Sep 28",
        signal: "SALARY",
      },
      {
        id: "n2",
        merchant: "Spotify + gym",
        category: "Subscriptions",
        amount: -32.98,
        date: "Sep 26",
        signal: "RECURRING",
      },
      {
        id: "n3",
        merchant: "Card payments",
        category: "Everyday spending",
        amount: -186.4,
        date: "Sep 24",
        signal: "CARD",
      },
      {
        id: "n4",
        merchant: "Savings transfer",
        category: "Savings",
        amount: -150,
        date: "Sep 22",
        signal: "SAVINGS",
      },
      {
        id: "n5",
        merchant: "Colruyt",
        category: "Groceries",
        amount: -41.2,
        date: "Sep 20",
      },
    ],
  },
  analysisSignals: [
    { id: "s1", from: "Rental deposit", to: "HOUSING" },
    { id: "s2", from: "IKEA", to: "HOME" },
    { id: "s3", from: "Brico", to: "HOME IMPROVEMENT" },
    { id: "s4", from: "Cambio van", to: "MOBILITY" },
  ],
  noahAnalysisSignals: [
    { id: "ns1", from: "First salary", to: "INCOME" },
    { id: "ns2", from: "Subscriptions", to: "RECURRING" },
    { id: "ns3", from: "Card activity", to: "CARDS" },
    { id: "ns4", from: "Savings transfer", to: "SAVINGS" },
  ],
  moving: {
    daysToGo: 12,
    moveDate: "October 12",
    rentDate: "October 1",
    oldRent: 850,
    buffer: 1240,
    balanceToday: 3842,
    deposit: 2100,
    homePurchases: 1060,
  },
  firstJob: {
    salary: 2100,
    payday: "28th",
    savingsGoal: 500,
    savingsNow: 150,
    recurringTotal: 32.98,
  },
  personas: [
    {
      id: "emma",
      initial: "E",
      name: "Emma",
      mode: "MOVING",
      modules: ["Standing orders", "Cashflow", "Home setup", "Moving day"],
    },
    {
      id: "noah",
      initial: "N",
      name: "Noah",
      mode: "FIRST JOB",
      modules: ["Salary", "Savings", "Card readiness", "Recurring"],
    },
    {
      id: "sarah",
      initial: "S",
      name: "Sarah",
      mode: "TRAVEL",
      modules: ["Card readiness", "Insurance", "Foreign spending"],
    },
    {
      id: "thomas",
      initial: "T",
      name: "Thomas",
      mode: "NEW FAMILY",
      modules: ["Recurring expenses", "Insurance", "Savings"],
    },
  ],
};
