window.KBC_DEMO = {
  emma: {
    name: "Emma",
    balance: 3842.61,
    greeting: "Good evening, Emma",
    transactions: [
      {
        id: "1",
        merchant: "Rental deposit",
        category: "Housing",
        amount: -2100,
        date: "Sep 14",
        signal: "HOUSING",
      },
      {
        id: "2",
        merchant: "IKEA",
        category: "Home",
        amount: -847,
        date: "Sep 12",
        signal: "HOME",
      },
      {
        id: "3",
        merchant: "Brico",
        category: "Home improvement",
        amount: -213,
        date: "Sep 10",
        signal: "HOME",
      },
      {
        id: "4",
        merchant: "Cambio",
        category: "Van rental",
        amount: -64,
        date: "Sep 9",
        signal: "MOVING",
      },
      {
        id: "5",
        merchant: "Salary",
        category: "Income",
        amount: 2850,
        date: "Sep 1",
      },
      {
        id: "6",
        merchant: "Colruyt",
        category: "Groceries",
        amount: -68.42,
        date: "Aug 30",
      },
    ],
  },
  analysisSignals: [
    { id: "s1", from: "Rental deposit", to: "HOUSING" },
    { id: "s2", from: "IKEA", to: "HOME" },
    { id: "s3", from: "Brico", to: "HOME IMPROVEMENT" },
    { id: "s4", from: "Cambio van", to: "MOBILITY" },
  ],
  moving: {
    daysToGo: 12,
    moveDate: "October 12",
    rentDate: "October 1",
    oldRent: 850,
    buffer: 1240,
    balanceToday: 3842,
    deposit: 2100,
    homePurchases: 1060,
  },
  personas: [
    {
      id: "emma",
      initial: "E",
      name: "Emma",
      mode: "MOVING",
      modules: ["Standing orders", "Cashflow", "Home setup"],
    },
    {
      id: "noah",
      initial: "N",
      name: "Noah",
      mode: "FIRST JOB",
      modules: ["First salary", "Savings", "Cashflow"],
    },
    {
      id: "sarah",
      initial: "S",
      name: "Sarah",
      mode: "TRAVEL",
      modules: ["Card readiness", "Insurance", "Foreign spending"],
    },
    {
      id: "thomas",
      initial: "T",
      name: "Thomas",
      mode: "NEW FAMILY",
      modules: ["Recurring expenses", "Insurance", "Savings"],
    },
  ],
};
